// core/activeCryptos.js — FIAT‑PRO

export const ACTIVE_CRYPTO_LIST = [
  "APT-USDT","ARB-USDT","ASTER-USDT","ATOM-USDT","AVAX-USDT",
  "BCH-USDT","DOT-USDT","FET-USDT","HBAR-USDT","LTC-USDT",
  "OP-USDT","PEPE-USDT","SEI-USDT","SUI-USDT","TRUMP-USDT",
  "VIRTUAL-USDT","XRP-USDT"
];


export const UNIVERSE = [
  "APT-USDT","LINK-USDT","OP-USDT","SOL-USDT","BTC-USDT","FET-USDT",
  "RENDER-USDT","XRP-USDT","ARB-USDT","ATOM-USDT","BNB-USDT","DOT-USDT",
  "ETH-USDT","INJ-USDT","PEPE-USDT","TRUMP-USDT","ADA-USDT","ASTER-USDT",
  "AVAX-USDT","BCH-USDT","HBAR-USDT","NEAR-USDT","SEI-USDT","SUI-USDT",
  "VIRTUAL-USDT","LTC-USDT"
];
