// core/activeCryptos.js — FIAT‑PRO

export const ACTIVE_CRYPTO_LIST = [
  "APT-USDT","ARB-USDT","ATOM-USDT","AVAX-USDT","BCH-USDT",
  "DOT-USDT","FET-USDT","HBAR-USDT","LTC-USDT","OP-USDT",
  "PEPE-USDT","SEI-USDT","SUI-USDT","TRUMP-USDT","VIRTUAL-USDT",
  "XRP-USDT"
];
